export const environment = {
  production: true,
  baseUrl: 'https://localhost:8080',
  login:"login",
  auth:"auth",
  refresh:"refresh",
  confirmAccount : "confirmAccount",
  registration : "register",
  checkUsername : "checkUsername",
  checkEmail: "checkEmail",
  logout : "logout",
  resetPasswordMail : "resetPasswordMail",
  resetPassword : "resetPassword",
  resendPassCode : "resendPassCode",
  resendRegCode : "resendRegistrationCode",
  following : "following",
  usersFollowings : "usersFollowings",
  checkLoggedUser : "checkLoggedUser",
  getUserById : "getUserById",
  getUserProfileById : "getUserProfileById"
};
